import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    theme: {
        extend: {
            colors: {
                "brand": {
                    50: '#eff6ff',
                    100: '#dbeafe',
                    200: '#bfdbfe',
                    500: '#3b82f6',
                    600: '#2563eb',
                    700: '#1d4ed8',
                    800: '#1e40af',
                    900: '#1e3a8a',
                    950: '#0f172a'
                },
                "outline": "#727780",
                "outline-variant": "#c1c7d0",
                "tertiary-fixed": "#cfe5ff",
                "error-container": "#ffdad6",
                "tertiary-container": "#32475c",
                "inverse-surface": "#2e3134",
                "surface-tint": "#2b6290",
                "inverse-on-surface": "#f0f0f5",
                "primary-container": "#004875",
                "surface-bright": "#f9f9fd",
                "tertiary": "#1b3144",
                "on-tertiary-fixed": "#051d30",
                "on-error-container": "#93000a",
                "warning-main": "#d97706",
                "secondary": "#08629c",
                "success-main": "#059669",
                "on-secondary-fixed": "#001d34",
                "surface": "#f9f9fd",
                "surface-dim": "#d9dade",
                "on-secondary-fixed-variant": "#004a78",
                "on-secondary-container": "#004c7c",
                "text-secondary": "#414750",
                "primary-fixed-dim": "#99cbff",
                "on-tertiary-fixed-variant": "#34495d",
                "primary-fixed": "#cfe5ff",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed": "#001d34",
                "inverse-primary": "#99cbff",
                "on-surface-variant": "#41474f",
                "secondary-fixed": "#cfe5ff",
                "surface-container-low": "#f3f3f8",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "tertiary-fixed-dim": "#b3c9e2",
                "error-main": "#ba1a1a",
                "background": "#f9f9fd",
                "on-background": "#191c1f",
                "on-surface": "#191c1f",
                "on-primary-container": "#85b7ea",
                "surface-container-high": "#e7e8ec",
                "surface-variant": "#e1e2e6",
                "canvas-bg": "#f7f9ff",
                "on-tertiary-container": "#9fb5ce",
                "surface-glass": "rgba(255, 255, 255, 0.85)",
                "success-container": "#d1fae5",
                "on-secondary": "#ffffff",
                "secondary-fixed-dim": "#99cbff",
                "border-glass": "rgba(192, 199, 210, 0.4)",
                "surface-container": "#edeef2",
                "surface-container-highest": "#e1e2e6",
                "on-tertiary": "#ffffff",
                "secondary-container": "#7dbefe",
                "primary": "#003152",
                "text-main": "#151c23",
                "on-primary-fixed-variant": "#044a77",
                "on-primary": "#ffffff"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "gutter": "1rem",
                "margin-mobile": "1rem",
                "margin-desktop": "2rem",
                "section-gap": "2rem",
                "card-padding": "1.5rem",
                "max-width": "1600px"
            },
            fontFamily: {
                "headline-lg": ['"Plus Jakarta Sans"', "sans-serif"],
                "label-md": ['"Plus Jakarta Sans"', "sans-serif"],
                "title-md": ['"Plus Jakarta Sans"', "sans-serif"],
                "headline-xl": ['"Plus Jakarta Sans"', "sans-serif"],
                "body-md": ['"Plus Jakarta Sans"', "sans-serif"],
                "title-lg": ['"Plus Jakarta Sans"', "sans-serif"],
                "body-sm": ['"Plus Jakarta Sans"', "sans-serif"],
                "sans": ['"Plus Jakarta Sans"', ...defaultTheme.fontFamily.sans],
            },
            boxShadow: {
                'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.05), 0 4px 6px -2px rgba(0, 0, 0, 0.03)',
                'card': '0 10px 25px -5px rgba(15, 23, 42, 0.06), 0 8px 10px -6px rgba(15, 23, 42, 0.04)',
                '2xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
            },
            fontSize: {
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.025em", "fontWeight": "700"}],
                "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
                "title-md": ["16px", {"lineHeight": "24px", "fontWeight": "600"}],
                "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.025em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
            }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
};
